### ISSUE TITLE
Go-Button in endless mode goes to previous level instead of next

### ISSUE THREAD

**Issue by klaviartur** [ochadenas/cpudefense#144] opened 2024-03-25 19:49 UTC
When a level is won in endless mode the Go-Button on the "Mission briefing"/"Did you know" screen in between levels restarts the previous level instead of starting the next.
The same happens if you go to heros screen and tap on "start level" there.

Edit: This seems to happen only when winning for the first time. Probably the new level is not generated yet and therefore is not bound to the button.

**Comment by ochadenas** [comment] 2024-07-14 19:49
I can't reproduce this in 1.36, and like to close this issue. If the bug persists, please re-open it.

**Closed by ochadenas** 2024-07-14 19:49 UTC
