### ISSUE TITLE
"Select level" sorting

### ISSUE THREAD

**Issue by JackMauro** [ochadenas/cpudefense#52] opened 2023-10-29 23:28 UTC
The "select level" page seem to be sorted randomly instead of numerically per level number on version 1.22 downloaded from F-Droid.

On my Xiaomi Redmi 5 (Qualcom Snapdragon 625, 64bit Arm v8a; 4GB Ram, 64GB storage; Display resolution 1080*2160; GPU Adreno 506 ) Plus with android 7.1.2 rooted some levels stays colored in white instead of green/orange even after been player.

After complete level 28 "normal", all levels disappear exept level 11 and 28; The same for "turbo" levels. 
Because of that I cannot replay previous levels with the benefit of heroes after complete the last level.

Is this intentional or a bug?

**Comment by ochadenas** [comment] 2023-10-30 17:01
No, this is not intentional, and on my device the level list doesn't do this ...

I suppose this is caused by the same problem as issue 51. The levels that have been played are stored in the app's preferences, so a problem there could well mess up the level list.

**Comment by ochadenas** [comment] 2023-11-01 17:54
> BTW, why levels are sorted in this "strange" order?

Because your "preferences" file is seriously messed up, I'd say. The list of levels is saved in these preferences.

Have you tried to start a new game (which should clear this list)? There is not much one can do anyway.

**Comment by JackMauro** [comment] 2023-11-01 18:18
The screenshot is took AFTER restart the game, BEFORE of the first crash.

Now, a few levels played, the file appear to be really, really messed up:
[prefs.xml.zip](https://github.com/ochadenas/cpudefense/files/13230491/prefs.xml.zip)

So the issue is: what has corrupted the file? crash during the save process or something else?

**Comment by ochadenas** [comment] 2024-01-16 11:52
I still have no idea :(

In 1.27, the thumbnails have been moved to a separate file, this will hopefully take out some problems here. Still I do not understand why after starting a new game, there are any levels displayed at all in the selection screen. That just shouldn't happen.

**Comment by ochadenas** [comment] 2024-02-10 08:12
I'm closing this issue because I'm unable to reproduce it. I hope that whatever bug this has caused, it is fixed by now. Please open another issue it the problem appears again.

**Closed by ochadenas** 2024-02-10 08:12 UTC
