### ISSUE TITLE
Game crashes a lot

### ISSUE THREAD

**Issue by JackMauro** [ochadenas/cpudefense#51] opened 2023-10-29 23:21 UTC
On my Xiaomi Redmi 5 (Qualcom Snapdragon 625, 64bit Arm v8a; 4GB Ram, 64GB storage; Display resolution 1080*2160; GPU Adreno 506 ) Plus with android 7.1.2 rooted the game, version 1.22 downloaded from F-Droid, crashes frequently.

This is a non complete list of crash points:
- Il "disable background" is not checked, the game crashes as soon as i tap "Enter" on any level (including 1). (same as issue #27 i think)
- Sometimes crashes when tap on "Heroes".
- Sometimes crashes when spending coins hiring heroes (when happens, it can be bugabused: the hire is saved, the substract of coins is not).
- Sometimes "restart level" crashes the game.
- After a crash, "resume" or "Play level XX" crashes again: need to select a level.
- If the display turns off for power save, then turn it back on, the game crashes (same as issue #47)
- If i switch to another application, then i come back to the game, it crashes.

How can I save a debug log with some more details to send you?

Thanks

**Comment by ochadenas** [comment] 2023-10-30 16:58
I'm at a loss here. I can't reproduce the crashes you describe, and except the problem of issue #27 (which is directly connected to loading of background pictures and is probably a memory management issue), there are no other report of crashes like yours. So I think that it is not linked to the source code itself, but has some other cause.

Wild guess: Could the reason be a corrupted save file? I think in all of the situations mentioned the app tries to restore its state, so this might be a reason. As your device is rooted, you can probably access the app's preferences and share its contents.

Another hypothetical reason for crashes is that the game tries to determine the size of elements on the screen and calculates some negative numbers. Bugs like that show occasionally on very small or very high display resolutions. But your resolution of 1080*2160 is completely unconspicuous.


> (when happens, it can be bugabused: the hire is saved, the substract of coins is not).

This is fixed in 1.24

**Comment by JackMauro** [comment] 2023-11-01 17:11
This is a screenshot of one of the crashes, just after press "Resume" on main screen, after a clean quit:
![Screenshot_2023-11-01-13-30-30-993_com nolanlawson logcat](https://github.com/ochadenas/cpudefense/assets/12693862/1a3d4c72-49c1-401a-87f3-c45f3b7c7fb2)

Hope this may help.

**Comment by ochadenas** [comment] 2023-11-01 17:50
Hmm. That shows that the game doesn't know the dimensions of the screen, and so the calculation of the areas for the various elements fails. Android doesn't like bitmaps with size 0 and terminates the program.

 But it's hard to tell why we've come to this point. It has something to do with resuming the game. I still think that the saved state is somehow corrupted.

**Comment by JackMauro** [comment] 2023-11-01 18:09
I have added it to my previous comment (probably editing it after you have already read it).

**Comment by Sogolumbo** [comment] 2023-11-14 13:29
I also have the problem of many crashes. I was able to play up to level 11 with little or no crashes. But then suddenly the app started crashing everytime I pressed "play"/"Los"(German).
The app pauses, and then resumes to the home screen.
The crashing remains even after deleting app data, reinstalling the app and restarting my device.

I'm running version 1.26 of the app.
Andrios 6.0 (Marshmellow), 3Gb Ram, less than 1Gb of free internal storage.

**Comment by ochadenas** [comment] 2023-11-18 08:42
I have not been able to make any progress here, unfortunately. Still can't reproduce the issue. Maybe it has to do with switching between applications in an unfortunate moment, and then the save file gets corrupted and can't be recovered. But that's only a guess.

I'm going to split up the save file (which is all in one preferences file at the moment) into different parts that can be saved separately. In that way, there is less chance that a bug will destroy it. But this is not going to be an easy operation and will take several versions. 

Does your app still crash if you start a new game? (Of course, that is not a solution.)

**Comment by ochadenas** [comment] 2023-11-18 19:57
Another question: Are you using the button "Resume" or "Play level xx"?

**Comment by ochadenas** [comment] 2024-01-16 11:47
I'd like to close this issue, because I can't really reproduce it, and on the other hand there have been several improvements and bug fixes in 1.27, so there is hope that the problem does no longer appear. 

Please re-open the issue (or create a new one) if it persists.

**Closed** 2024-01-16 11:52 UTC
