### ISSUE TITLE
Firing base heroes won't reset unlocked

### ISSUE THREAD

**Issue by Lik-the-Fluffin** [ochadenas/cpudefense#161] opened 2024-07-13 03:11 UTC
For example:
1. buy speed upgrades to unlock range ones 
2. buy any amount of range upgrade
3. sell speed upgrade
In result you still have range extension even if it's locked and invisible

**Comment by ochadenas** [comment] 2024-07-13 07:05
Yes, that's true. This holds for all heroes that depend on an other; if the prerequisites are no longer met, the hero is still there. Invsibly.

I'm not quite sure how to change this. I don't like the idea that a hero gets sold automatically without explicitly having requested this. Neither do I like the idea that a hero can't be sold, just because there are still dependencies. So I'd like to call this a feature, not a bug ;)

Anyway, this is only an issue in the normal series. After that, all heroes are always available.

**Comment by ochadenas** [comment] 2024-07-26 14:17
I close this as "works as intended".

**Comment by ochadenas** [comment] 2024-07-26 14:18
-

**Closed by ochadenas** 2024-07-26 14:18 UTC
